package model;
// Generated 16/05/2014 08:45:15 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Extra generated by hbm2java
 */
@Entity
@Table(name="extra"
    ,catalog="arcitecar"
)
public class Extra  implements java.io.Serializable {


     private Integer idextra;
     private int identificacion;
     private String nombres;
     private String apellidos;
     private String sexo;
     private String peso;
     private String estatura;
     private String telefono;
     private Set imagens = new HashSet(0);

    public Extra() {
        this.idextra=0;
    }

	
    public Extra(int identificacion, String nombres, String apellidos, String sexo, String peso, String estatura, String telefono) {
        this.identificacion = identificacion;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.sexo = sexo;
        this.peso = peso;
        this.estatura = estatura;
        this.telefono = telefono;
    }
    public Extra(int identificacion, String nombres, String apellidos, String sexo, String peso, String estatura, String telefono, Set imagens) {
       this.identificacion = identificacion;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.sexo = sexo;
       this.peso = peso;
       this.estatura = estatura;
       this.telefono = telefono;
       this.imagens = imagens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idextra", unique=true, nullable=false)
    public Integer getIdextra() {
        return this.idextra;
    }
    
    public void setIdextra(Integer idextra) {
        this.idextra = idextra;
    }

    
    @Column(name="identificacion", nullable=false)
    public int getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(int identificacion) {
        this.identificacion = identificacion;
    }

    
    @Column(name="nombres", nullable=false, length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", nullable=false, length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="sexo", nullable=false, length=15)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="peso", nullable=false, length=10)
    public String getPeso() {
        return this.peso;
    }
    
    public void setPeso(String peso) {
        this.peso = peso;
    }

    
    @Column(name="estatura", nullable=false, length=10)
    public String getEstatura() {
        return this.estatura;
    }
    
    public void setEstatura(String estatura) {
        this.estatura = estatura;
    }

    
    @Column(name="telefono", nullable=false, length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="extra")
    public Set getImagens() {
        return this.imagens;
    }
    
    public void setImagens(Set imagens) {
        this.imagens = imagens;
    }




}


