package model;
// Generated 16/05/2014 08:45:15 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Imagen generated by hbm2java
 */
@Entity
@Table(name="imagen"
    ,catalog="arcitecar"
)
public class Imagen  implements java.io.Serializable {


     private Integer idimagen;
     private Extra extra;
     private byte[] foto;
     private String descripcion;
     private int orden;

    public Imagen() {
        this.idimagen = 0;
        this.extra = new Extra();
    }

	
    public Imagen(Extra extra, String descripcion, int orden) {
        this.extra = extra;
        this.descripcion = descripcion;
        this.orden = orden;
    }
    public Imagen(Extra extra, byte[] foto, String descripcion, int orden) {
       this.extra = extra;
       this.foto = foto;
       this.descripcion = descripcion;
       this.orden = orden;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idimagen", unique=true, nullable=false)
    public Integer getIdimagen() {
        return this.idimagen;
    }
    
    public void setIdimagen(Integer idimagen) {
        this.idimagen = idimagen;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idextra", nullable=false)
    public Extra getExtra() {
        return this.extra;
    }
    
    public void setExtra(Extra extra) {
        this.extra = extra;
    }
    
    @Column(name="foto")
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }

    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name="orden", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }

}